void TrackClusterDistanceCut_Zuds380_totalEnergyRecoVsTruth()
{
//=========Macro generated from canvas: c1/A Simple Graph Example
//=========  (Mon Mar  5 13:11:02 2018) by ROOT version6.08/00
   TCanvas *c1 = new TCanvas("c1", "A Simple Graph Example",2,51,800,700);
   gStyle->SetOptStat(0);
   gStyle->SetOptTitle(0);
   c1->SetHighLightColor(2);
   c1->Range(142.88,-1982.201,478.88,9030.028);
   c1->SetFillColor(0);
   c1->SetBorderMode(0);
   c1->SetBorderSize(2);
   c1->SetTickx(1);
   c1->SetTicky(1);
   c1->SetPhi(150);
   c1->SetLeftMargin(0.17);
   c1->SetRightMargin(0.08);
   c1->SetTopMargin(0.08);
   c1->SetBottomMargin(0.18);
   c1->SetFrameLineWidth(2);
   c1->SetFrameBorderMode(0);
   c1->SetFrameLineWidth(2);
   c1->SetFrameBorderMode(0);
   
   TH1F *hist_pfoTargetsEnergyTotal__4 = new TH1F("hist_pfoTargetsEnergyTotal__4","hist_pfoTargetsEnergyTotal",125,0,500);
   hist_pfoTargetsEnergyTotal__4->SetBinContent(95,7761);
   hist_pfoTargetsEnergyTotal__4->SetBinContent(96,2139);
   hist_pfoTargetsEnergyTotal__4->SetEntries(9900);
   hist_pfoTargetsEnergyTotal__4->SetStats(0);
   hist_pfoTargetsEnergyTotal__4->SetLineWidth(2);
   hist_pfoTargetsEnergyTotal__4->SetMarkerStyle(0);
   hist_pfoTargetsEnergyTotal__4->SetMarkerSize(1.2);
   hist_pfoTargetsEnergyTotal__4->GetXaxis()->SetTitle("Energy [GeV]");
   hist_pfoTargetsEnergyTotal__4->GetXaxis()->SetRange(51,113);
   hist_pfoTargetsEnergyTotal__4->GetXaxis()->SetNdivisions(506);
   hist_pfoTargetsEnergyTotal__4->GetXaxis()->SetLabelFont(42);
   hist_pfoTargetsEnergyTotal__4->GetXaxis()->SetLabelOffset(0.015);
   hist_pfoTargetsEnergyTotal__4->GetXaxis()->SetLabelSize(0.06);
   hist_pfoTargetsEnergyTotal__4->GetXaxis()->SetTitleSize(0.07);
   hist_pfoTargetsEnergyTotal__4->GetXaxis()->SetTitleFont(42);
   hist_pfoTargetsEnergyTotal__4->GetYaxis()->SetTitle("Counts");
   hist_pfoTargetsEnergyTotal__4->GetYaxis()->SetNdivisions(506);
   hist_pfoTargetsEnergyTotal__4->GetYaxis()->SetLabelFont(42);
   hist_pfoTargetsEnergyTotal__4->GetYaxis()->SetLabelOffset(0.015);
   hist_pfoTargetsEnergyTotal__4->GetYaxis()->SetLabelSize(0.06);
   hist_pfoTargetsEnergyTotal__4->GetYaxis()->SetTitleSize(0.07);
   hist_pfoTargetsEnergyTotal__4->GetYaxis()->SetTitleOffset(1.2);
   hist_pfoTargetsEnergyTotal__4->GetYaxis()->SetTitleFont(42);
   hist_pfoTargetsEnergyTotal__4->GetZaxis()->SetLabelFont(42);
   hist_pfoTargetsEnergyTotal__4->GetZaxis()->SetLabelOffset(0.015);
   hist_pfoTargetsEnergyTotal__4->GetZaxis()->SetLabelSize(0.06);
   hist_pfoTargetsEnergyTotal__4->GetZaxis()->SetTitleSize(0.07);
   hist_pfoTargetsEnergyTotal__4->GetZaxis()->SetTitleOffset(1.2);
   hist_pfoTargetsEnergyTotal__4->GetZaxis()->SetTitleFont(42);
   hist_pfoTargetsEnergyTotal__4->Draw("HIST");
   
   TH1F *hist_pfoEnergyTotal__5 = new TH1F("hist_pfoEnergyTotal__5","hist_pfoEnergyTotal",125,0,500);
   hist_pfoEnergyTotal__5->SetBinContent(11,1);
   hist_pfoEnergyTotal__5->SetBinContent(14,1);
   hist_pfoEnergyTotal__5->SetBinContent(15,1);
   hist_pfoEnergyTotal__5->SetBinContent(16,3);
   hist_pfoEnergyTotal__5->SetBinContent(18,3);
   hist_pfoEnergyTotal__5->SetBinContent(20,3);
   hist_pfoEnergyTotal__5->SetBinContent(23,1);
   hist_pfoEnergyTotal__5->SetBinContent(24,3);
   hist_pfoEnergyTotal__5->SetBinContent(25,1);
   hist_pfoEnergyTotal__5->SetBinContent(27,2);
   hist_pfoEnergyTotal__5->SetBinContent(30,1);
   hist_pfoEnergyTotal__5->SetBinContent(31,1);
   hist_pfoEnergyTotal__5->SetBinContent(32,1);
   hist_pfoEnergyTotal__5->SetBinContent(34,2);
   hist_pfoEnergyTotal__5->SetBinContent(35,1);
   hist_pfoEnergyTotal__5->SetBinContent(37,4);
   hist_pfoEnergyTotal__5->SetBinContent(39,1);
   hist_pfoEnergyTotal__5->SetBinContent(40,1);
   hist_pfoEnergyTotal__5->SetBinContent(42,3);
   hist_pfoEnergyTotal__5->SetBinContent(43,1);
   hist_pfoEnergyTotal__5->SetBinContent(44,1);
   hist_pfoEnergyTotal__5->SetBinContent(45,3);
   hist_pfoEnergyTotal__5->SetBinContent(47,1);
   hist_pfoEnergyTotal__5->SetBinContent(48,1);
   hist_pfoEnergyTotal__5->SetBinContent(49,2);
   hist_pfoEnergyTotal__5->SetBinContent(51,2);
   hist_pfoEnergyTotal__5->SetBinContent(52,2);
   hist_pfoEnergyTotal__5->SetBinContent(53,2);
   hist_pfoEnergyTotal__5->SetBinContent(54,3);
   hist_pfoEnergyTotal__5->SetBinContent(55,1);
   hist_pfoEnergyTotal__5->SetBinContent(56,4);
   hist_pfoEnergyTotal__5->SetBinContent(57,4);
   hist_pfoEnergyTotal__5->SetBinContent(59,5);
   hist_pfoEnergyTotal__5->SetBinContent(60,5);
   hist_pfoEnergyTotal__5->SetBinContent(61,2);
   hist_pfoEnergyTotal__5->SetBinContent(62,3);
   hist_pfoEnergyTotal__5->SetBinContent(63,3);
   hist_pfoEnergyTotal__5->SetBinContent(64,6);
   hist_pfoEnergyTotal__5->SetBinContent(65,2);
   hist_pfoEnergyTotal__5->SetBinContent(66,1);
   hist_pfoEnergyTotal__5->SetBinContent(67,3);
   hist_pfoEnergyTotal__5->SetBinContent(68,6);
   hist_pfoEnergyTotal__5->SetBinContent(69,4);
   hist_pfoEnergyTotal__5->SetBinContent(70,3);
   hist_pfoEnergyTotal__5->SetBinContent(71,3);
   hist_pfoEnergyTotal__5->SetBinContent(72,7);
   hist_pfoEnergyTotal__5->SetBinContent(73,7);
   hist_pfoEnergyTotal__5->SetBinContent(74,6);
   hist_pfoEnergyTotal__5->SetBinContent(75,6);
   hist_pfoEnergyTotal__5->SetBinContent(76,8);
   hist_pfoEnergyTotal__5->SetBinContent(77,4);
   hist_pfoEnergyTotal__5->SetBinContent(78,13);
   hist_pfoEnergyTotal__5->SetBinContent(79,14);
   hist_pfoEnergyTotal__5->SetBinContent(80,16);
   hist_pfoEnergyTotal__5->SetBinContent(81,17);
   hist_pfoEnergyTotal__5->SetBinContent(82,27);
   hist_pfoEnergyTotal__5->SetBinContent(83,20);
   hist_pfoEnergyTotal__5->SetBinContent(84,27);
   hist_pfoEnergyTotal__5->SetBinContent(85,45);
   hist_pfoEnergyTotal__5->SetBinContent(86,59);
   hist_pfoEnergyTotal__5->SetBinContent(87,82);
   hist_pfoEnergyTotal__5->SetBinContent(88,156);
   hist_pfoEnergyTotal__5->SetBinContent(89,199);
   hist_pfoEnergyTotal__5->SetBinContent(90,288);
   hist_pfoEnergyTotal__5->SetBinContent(91,480);
   hist_pfoEnergyTotal__5->SetBinContent(92,671);
   hist_pfoEnergyTotal__5->SetBinContent(93,955);
   hist_pfoEnergyTotal__5->SetBinContent(94,1221);
   hist_pfoEnergyTotal__5->SetBinContent(95,1394);
   hist_pfoEnergyTotal__5->SetBinContent(96,1299);
   hist_pfoEnergyTotal__5->SetBinContent(97,994);
   hist_pfoEnergyTotal__5->SetBinContent(98,613);
   hist_pfoEnergyTotal__5->SetBinContent(99,421);
   hist_pfoEnergyTotal__5->SetBinContent(100,270);
   hist_pfoEnergyTotal__5->SetBinContent(101,139);
   hist_pfoEnergyTotal__5->SetBinContent(102,83);
   hist_pfoEnergyTotal__5->SetBinContent(103,63);
   hist_pfoEnergyTotal__5->SetBinContent(104,48);
   hist_pfoEnergyTotal__5->SetBinContent(105,33);
   hist_pfoEnergyTotal__5->SetBinContent(106,23);
   hist_pfoEnergyTotal__5->SetBinContent(107,14);
   hist_pfoEnergyTotal__5->SetBinContent(108,11);
   hist_pfoEnergyTotal__5->SetBinContent(109,11);
   hist_pfoEnergyTotal__5->SetBinContent(110,5);
   hist_pfoEnergyTotal__5->SetBinContent(111,5);
   hist_pfoEnergyTotal__5->SetBinContent(112,9);
   hist_pfoEnergyTotal__5->SetBinContent(113,2);
   hist_pfoEnergyTotal__5->SetBinContent(114,4);
   hist_pfoEnergyTotal__5->SetBinContent(115,2);
   hist_pfoEnergyTotal__5->SetBinContent(116,1);
   hist_pfoEnergyTotal__5->SetBinContent(117,1);
   hist_pfoEnergyTotal__5->SetBinContent(118,1);
   hist_pfoEnergyTotal__5->SetBinContent(119,1);
   hist_pfoEnergyTotal__5->SetBinContent(120,1);
   hist_pfoEnergyTotal__5->SetBinContent(121,2);
   hist_pfoEnergyTotal__5->SetBinContent(123,2);
   hist_pfoEnergyTotal__5->SetBinContent(124,3);
   hist_pfoEnergyTotal__5->SetBinContent(125,2);
   hist_pfoEnergyTotal__5->SetBinContent(126,8);
   hist_pfoEnergyTotal__5->SetEntries(9900);
   hist_pfoEnergyTotal__5->SetStats(0);

   Int_t ci;      // for color index setting
   TColor *color; // for color definition with alpha
   ci = TColor::GetColor("#ff6666");
   hist_pfoEnergyTotal__5->SetLineColor(ci);
   hist_pfoEnergyTotal__5->SetLineWidth(2);

   ci = TColor::GetColor("#ff6666");
   hist_pfoEnergyTotal__5->SetMarkerColor(ci);
   hist_pfoEnergyTotal__5->SetMarkerStyle(0);
   hist_pfoEnergyTotal__5->SetMarkerSize(1.2);
   hist_pfoEnergyTotal__5->GetXaxis()->SetRange(1,1000);
   hist_pfoEnergyTotal__5->GetXaxis()->SetNdivisions(506);
   hist_pfoEnergyTotal__5->GetXaxis()->SetLabelFont(42);
   hist_pfoEnergyTotal__5->GetXaxis()->SetLabelOffset(0.015);
   hist_pfoEnergyTotal__5->GetXaxis()->SetLabelSize(0.06);
   hist_pfoEnergyTotal__5->GetXaxis()->SetTitleSize(0.07);
   hist_pfoEnergyTotal__5->GetXaxis()->SetTitleFont(42);
   hist_pfoEnergyTotal__5->GetYaxis()->SetNdivisions(506);
   hist_pfoEnergyTotal__5->GetYaxis()->SetLabelFont(42);
   hist_pfoEnergyTotal__5->GetYaxis()->SetLabelOffset(0.015);
   hist_pfoEnergyTotal__5->GetYaxis()->SetLabelSize(0.06);
   hist_pfoEnergyTotal__5->GetYaxis()->SetTitleSize(0.07);
   hist_pfoEnergyTotal__5->GetYaxis()->SetTitleOffset(1.2);
   hist_pfoEnergyTotal__5->GetYaxis()->SetTitleFont(42);
   hist_pfoEnergyTotal__5->GetZaxis()->SetLabelFont(42);
   hist_pfoEnergyTotal__5->GetZaxis()->SetLabelOffset(0.015);
   hist_pfoEnergyTotal__5->GetZaxis()->SetLabelSize(0.06);
   hist_pfoEnergyTotal__5->GetZaxis()->SetTitleSize(0.07);
   hist_pfoEnergyTotal__5->GetZaxis()->SetTitleOffset(1.2);
   hist_pfoEnergyTotal__5->GetZaxis()->SetTitleFont(42);
   hist_pfoEnergyTotal__5->Draw("HISTsame");
   
   TLegend *leg = new TLegend(0.2,0.6,0.6,0.9,NULL,"brNDC");
   leg->SetBorderSize(0);
   leg->SetTextFont(62);
   leg->SetLineColor(1);
   leg->SetLineStyle(1);
   leg->SetLineWidth(2);
   leg->SetFillColor(0);
   leg->SetFillStyle(1001);
   TLegendEntry *entry=leg->AddEntry("hist_pfoTargetsEnergyTotal","Truth (380.00 GeV)","lp");
   entry->SetLineColor(1);
   entry->SetLineStyle(1);
   entry->SetLineWidth(2);
   entry->SetMarkerColor(1);
   entry->SetMarkerSize(1.2);
   entry->SetTextFont(62);
   entry=leg->AddEntry("hist_pfoEnergyTotal","Nominal (374.95 GeV)","lp");

   ci = TColor::GetColor("#ff6666");
   entry->SetLineColor(ci);
   entry->SetLineStyle(1);
   entry->SetLineWidth(2);

   ci = TColor::GetColor("#ff6666");
   entry->SetMarkerColor(ci);
   entry->SetMarkerSize(1.2);
   entry->SetTextFont(62);
   leg->Draw();
   c1->Modified();
   c1->cd();
   c1->SetSelected(c1);
}
