void TrackClusterDistanceCut_Zuds91_totalEnergyRecoVsTruth()
{
//=========Macro generated from canvas: c1/A Simple Graph Example
//=========  (Mon Mar  5 13:11:09 2018) by ROOT version6.08/00
   TCanvas *c1 = new TCanvas("c1", "A Simple Graph Example",2,51,800,700);
   gStyle->SetOptStat(0);
   gStyle->SetOptTitle(0);
   c1->SetHighLightColor(2);
   c1->Range(-27.2,-1913.753,132.8,8718.207);
   c1->SetFillColor(0);
   c1->SetBorderMode(0);
   c1->SetBorderSize(2);
   c1->SetTickx(1);
   c1->SetTicky(1);
   c1->SetPhi(150);
   c1->SetLeftMargin(0.17);
   c1->SetRightMargin(0.08);
   c1->SetTopMargin(0.08);
   c1->SetBottomMargin(0.18);
   c1->SetFrameLineWidth(2);
   c1->SetFrameBorderMode(0);
   c1->SetFrameLineWidth(2);
   c1->SetFrameBorderMode(0);
   
   TH1F *hist_pfoTargetsEnergyTotal__17 = new TH1F("hist_pfoTargetsEnergyTotal__17","hist_pfoTargetsEnergyTotal",500,0,500);
   hist_pfoTargetsEnergyTotal__17->SetBinContent(91,7493);
   hist_pfoTargetsEnergyTotal__17->SetBinContent(92,2507);
   hist_pfoTargetsEnergyTotal__17->SetEntries(10000);
   hist_pfoTargetsEnergyTotal__17->SetStats(0);
   hist_pfoTargetsEnergyTotal__17->SetLineWidth(2);
   hist_pfoTargetsEnergyTotal__17->SetMarkerStyle(0);
   hist_pfoTargetsEnergyTotal__17->SetMarkerSize(1.2);
   hist_pfoTargetsEnergyTotal__17->GetXaxis()->SetTitle("Energy [GeV]");
   hist_pfoTargetsEnergyTotal__17->GetXaxis()->SetRange(1,120);
   hist_pfoTargetsEnergyTotal__17->GetXaxis()->SetNdivisions(506);
   hist_pfoTargetsEnergyTotal__17->GetXaxis()->SetLabelFont(42);
   hist_pfoTargetsEnergyTotal__17->GetXaxis()->SetLabelOffset(0.015);
   hist_pfoTargetsEnergyTotal__17->GetXaxis()->SetLabelSize(0.06);
   hist_pfoTargetsEnergyTotal__17->GetXaxis()->SetTitleSize(0.07);
   hist_pfoTargetsEnergyTotal__17->GetXaxis()->SetTitleFont(42);
   hist_pfoTargetsEnergyTotal__17->GetYaxis()->SetTitle("Counts");
   hist_pfoTargetsEnergyTotal__17->GetYaxis()->SetNdivisions(506);
   hist_pfoTargetsEnergyTotal__17->GetYaxis()->SetLabelFont(42);
   hist_pfoTargetsEnergyTotal__17->GetYaxis()->SetLabelOffset(0.015);
   hist_pfoTargetsEnergyTotal__17->GetYaxis()->SetLabelSize(0.06);
   hist_pfoTargetsEnergyTotal__17->GetYaxis()->SetTitleSize(0.07);
   hist_pfoTargetsEnergyTotal__17->GetYaxis()->SetTitleOffset(1.2);
   hist_pfoTargetsEnergyTotal__17->GetYaxis()->SetTitleFont(42);
   hist_pfoTargetsEnergyTotal__17->GetZaxis()->SetLabelFont(42);
   hist_pfoTargetsEnergyTotal__17->GetZaxis()->SetLabelOffset(0.015);
   hist_pfoTargetsEnergyTotal__17->GetZaxis()->SetLabelSize(0.06);
   hist_pfoTargetsEnergyTotal__17->GetZaxis()->SetTitleSize(0.07);
   hist_pfoTargetsEnergyTotal__17->GetZaxis()->SetTitleOffset(1.2);
   hist_pfoTargetsEnergyTotal__17->GetZaxis()->SetTitleFont(42);
   hist_pfoTargetsEnergyTotal__17->Draw("HIST");
   
   TH1F *hist_pfoEnergyTotal__18 = new TH1F("hist_pfoEnergyTotal__18","hist_pfoEnergyTotal",500,0,500);
   hist_pfoEnergyTotal__18->SetBinContent(19,1);
   hist_pfoEnergyTotal__18->SetBinContent(22,1);
   hist_pfoEnergyTotal__18->SetBinContent(28,2);
   hist_pfoEnergyTotal__18->SetBinContent(33,1);
   hist_pfoEnergyTotal__18->SetBinContent(35,2);
   hist_pfoEnergyTotal__18->SetBinContent(37,1);
   hist_pfoEnergyTotal__18->SetBinContent(38,1);
   hist_pfoEnergyTotal__18->SetBinContent(40,1);
   hist_pfoEnergyTotal__18->SetBinContent(41,1);
   hist_pfoEnergyTotal__18->SetBinContent(42,1);
   hist_pfoEnergyTotal__18->SetBinContent(44,2);
   hist_pfoEnergyTotal__18->SetBinContent(45,1);
   hist_pfoEnergyTotal__18->SetBinContent(46,2);
   hist_pfoEnergyTotal__18->SetBinContent(48,1);
   hist_pfoEnergyTotal__18->SetBinContent(49,2);
   hist_pfoEnergyTotal__18->SetBinContent(50,2);
   hist_pfoEnergyTotal__18->SetBinContent(51,4);
   hist_pfoEnergyTotal__18->SetBinContent(53,1);
   hist_pfoEnergyTotal__18->SetBinContent(54,2);
   hist_pfoEnergyTotal__18->SetBinContent(55,4);
   hist_pfoEnergyTotal__18->SetBinContent(56,5);
   hist_pfoEnergyTotal__18->SetBinContent(57,5);
   hist_pfoEnergyTotal__18->SetBinContent(58,2);
   hist_pfoEnergyTotal__18->SetBinContent(59,5);
   hist_pfoEnergyTotal__18->SetBinContent(60,2);
   hist_pfoEnergyTotal__18->SetBinContent(61,2);
   hist_pfoEnergyTotal__18->SetBinContent(62,4);
   hist_pfoEnergyTotal__18->SetBinContent(63,3);
   hist_pfoEnergyTotal__18->SetBinContent(64,5);
   hist_pfoEnergyTotal__18->SetBinContent(65,7);
   hist_pfoEnergyTotal__18->SetBinContent(66,6);
   hist_pfoEnergyTotal__18->SetBinContent(67,4);
   hist_pfoEnergyTotal__18->SetBinContent(68,13);
   hist_pfoEnergyTotal__18->SetBinContent(69,2);
   hist_pfoEnergyTotal__18->SetBinContent(70,12);
   hist_pfoEnergyTotal__18->SetBinContent(71,7);
   hist_pfoEnergyTotal__18->SetBinContent(72,2);
   hist_pfoEnergyTotal__18->SetBinContent(73,7);
   hist_pfoEnergyTotal__18->SetBinContent(74,11);
   hist_pfoEnergyTotal__18->SetBinContent(75,11);
   hist_pfoEnergyTotal__18->SetBinContent(76,12);
   hist_pfoEnergyTotal__18->SetBinContent(77,29);
   hist_pfoEnergyTotal__18->SetBinContent(78,27);
   hist_pfoEnergyTotal__18->SetBinContent(79,37);
   hist_pfoEnergyTotal__18->SetBinContent(80,42);
   hist_pfoEnergyTotal__18->SetBinContent(81,64);
   hist_pfoEnergyTotal__18->SetBinContent(82,112);
   hist_pfoEnergyTotal__18->SetBinContent(83,132);
   hist_pfoEnergyTotal__18->SetBinContent(84,184);
   hist_pfoEnergyTotal__18->SetBinContent(85,266);
   hist_pfoEnergyTotal__18->SetBinContent(86,365);
   hist_pfoEnergyTotal__18->SetBinContent(87,528);
   hist_pfoEnergyTotal__18->SetBinContent(88,744);
   hist_pfoEnergyTotal__18->SetBinContent(89,896);
   hist_pfoEnergyTotal__18->SetBinContent(90,1094);
   hist_pfoEnergyTotal__18->SetBinContent(91,1136);
   hist_pfoEnergyTotal__18->SetBinContent(92,1054);
   hist_pfoEnergyTotal__18->SetBinContent(93,857);
   hist_pfoEnergyTotal__18->SetBinContent(94,660);
   hist_pfoEnergyTotal__18->SetBinContent(95,495);
   hist_pfoEnergyTotal__18->SetBinContent(96,313);
   hist_pfoEnergyTotal__18->SetBinContent(97,245);
   hist_pfoEnergyTotal__18->SetBinContent(98,171);
   hist_pfoEnergyTotal__18->SetBinContent(99,101);
   hist_pfoEnergyTotal__18->SetBinContent(100,78);
   hist_pfoEnergyTotal__18->SetBinContent(101,51);
   hist_pfoEnergyTotal__18->SetBinContent(102,39);
   hist_pfoEnergyTotal__18->SetBinContent(103,27);
   hist_pfoEnergyTotal__18->SetBinContent(104,19);
   hist_pfoEnergyTotal__18->SetBinContent(105,24);
   hist_pfoEnergyTotal__18->SetBinContent(106,9);
   hist_pfoEnergyTotal__18->SetBinContent(107,7);
   hist_pfoEnergyTotal__18->SetBinContent(108,8);
   hist_pfoEnergyTotal__18->SetBinContent(109,2);
   hist_pfoEnergyTotal__18->SetBinContent(110,3);
   hist_pfoEnergyTotal__18->SetBinContent(111,2);
   hist_pfoEnergyTotal__18->SetBinContent(112,2);
   hist_pfoEnergyTotal__18->SetBinContent(113,5);
   hist_pfoEnergyTotal__18->SetBinContent(114,6);
   hist_pfoEnergyTotal__18->SetBinContent(115,1);
   hist_pfoEnergyTotal__18->SetBinContent(117,2);
   hist_pfoEnergyTotal__18->SetBinContent(122,1);
   hist_pfoEnergyTotal__18->SetBinContent(132,1);
   hist_pfoEnergyTotal__18->SetBinContent(156,1);
   hist_pfoEnergyTotal__18->SetEntries(10000);
   hist_pfoEnergyTotal__18->SetStats(0);

   Int_t ci;      // for color index setting
   TColor *color; // for color definition with alpha
   ci = TColor::GetColor("#ff6666");
   hist_pfoEnergyTotal__18->SetLineColor(ci);
   hist_pfoEnergyTotal__18->SetLineWidth(2);

   ci = TColor::GetColor("#ff6666");
   hist_pfoEnergyTotal__18->SetMarkerColor(ci);
   hist_pfoEnergyTotal__18->SetMarkerStyle(0);
   hist_pfoEnergyTotal__18->SetMarkerSize(1.2);
   hist_pfoEnergyTotal__18->GetXaxis()->SetRange(1,1000);
   hist_pfoEnergyTotal__18->GetXaxis()->SetNdivisions(506);
   hist_pfoEnergyTotal__18->GetXaxis()->SetLabelFont(42);
   hist_pfoEnergyTotal__18->GetXaxis()->SetLabelOffset(0.015);
   hist_pfoEnergyTotal__18->GetXaxis()->SetLabelSize(0.06);
   hist_pfoEnergyTotal__18->GetXaxis()->SetTitleSize(0.07);
   hist_pfoEnergyTotal__18->GetXaxis()->SetTitleFont(42);
   hist_pfoEnergyTotal__18->GetYaxis()->SetNdivisions(506);
   hist_pfoEnergyTotal__18->GetYaxis()->SetLabelFont(42);
   hist_pfoEnergyTotal__18->GetYaxis()->SetLabelOffset(0.015);
   hist_pfoEnergyTotal__18->GetYaxis()->SetLabelSize(0.06);
   hist_pfoEnergyTotal__18->GetYaxis()->SetTitleSize(0.07);
   hist_pfoEnergyTotal__18->GetYaxis()->SetTitleOffset(1.2);
   hist_pfoEnergyTotal__18->GetYaxis()->SetTitleFont(42);
   hist_pfoEnergyTotal__18->GetZaxis()->SetLabelFont(42);
   hist_pfoEnergyTotal__18->GetZaxis()->SetLabelOffset(0.015);
   hist_pfoEnergyTotal__18->GetZaxis()->SetLabelSize(0.06);
   hist_pfoEnergyTotal__18->GetZaxis()->SetTitleSize(0.07);
   hist_pfoEnergyTotal__18->GetZaxis()->SetTitleOffset(1.2);
   hist_pfoEnergyTotal__18->GetZaxis()->SetTitleFont(42);
   hist_pfoEnergyTotal__18->Draw("HISTsame");
   
   TLegend *leg = new TLegend(0.2,0.6,0.6,0.9,NULL,"brNDC");
   leg->SetBorderSize(0);
   leg->SetTextFont(62);
   leg->SetLineColor(1);
   leg->SetLineStyle(1);
   leg->SetLineWidth(2);
   leg->SetFillColor(0);
   leg->SetFillStyle(1001);
   TLegendEntry *entry=leg->AddEntry("hist_pfoTargetsEnergyTotal","Truth (91.00 GeV)","lp");
   entry->SetLineColor(1);
   entry->SetLineStyle(1);
   entry->SetLineWidth(2);
   entry->SetMarkerColor(1);
   entry->SetMarkerSize(1.2);
   entry->SetTextFont(62);
   entry=leg->AddEntry("hist_pfoEnergyTotal","Nominal (89.96 GeV)","lp");

   ci = TColor::GetColor("#ff6666");
   entry->SetLineColor(ci);
   entry->SetLineStyle(1);
   entry->SetLineWidth(2);

   ci = TColor::GetColor("#ff6666");
   entry->SetMarkerColor(ci);
   entry->SetMarkerSize(1.2);
   entry->SetTextFont(62);
   leg->Draw();
   c1->Modified();
   c1->cd();
   c1->SetSelected(c1);
}
